management:
  endpoint:
    shutdown:
      enabled: false
    restart:
      enabled: false
    health:
      enabled: true
#  server:
#    port: 4452
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,refresh

logging:
  config: classpath:logback.xml
  level:
    org.springframework.cloud.consul: INFO
    com.jdcloud: ${JMESH_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yy-MM-dd.HH:mm:ss.SSS} [%-16t] %-5p %-22c{0}%X{ServiceId}%X{trace-id} - %m%n"
    file: "%d{yy-MM-dd.HH:mm:ss.SSS} [%-16t] %-5p %-22c{0}%X{ServiceId}%X{trace-id} - %m%n"
  file:
    path: ./logs/
    name: ${logging.file.path}spring.log

spring:
  application:
    name: jmsf-provider-demo
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  config:
#    import:
#      - optional:consul:127.0.0.1:8500
  cloud:
    loadbalancer:
      enabled: true
#      zone: ${spring.profiles.active}
#      configurations: zone-preference
#      retry:
#        max-retries-on-next-service-instance: 3
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
#        acl-token: 6fca9ebf-ab1d-8023-9348-e6e12649968f
        register-health-check: true
        prefer-ip-address: true
#        instance-id: provider-withZone-${random.int}
#        instance-group: provider
#        instance-zone: ${spring.profiles.active}
#        health-check-critical-timeout: 10s
        tags:
          - test
        metadata:
          cc: cc
      config:
        enabled: true
#        aclToken: 6fca9ebf-ab1d-8023-9348-e6e12649968f
        format: YAML
        import-check:
          enabled: false

    service-registry:
      enabled: true
      auto-registration:
        enabled: true
        register-management: true

  main:
    web-application-type: servlet

  profiles:
    active: '@activeProfile@'
#  config:
#    activate:
#      on-profile: '@activeProfile@'
