dynamic:
  commonData: aaa123
  intValue: 12
  stringValue: aaaa
  boolValue: true

jmsf:
  enabled: true
  tags:
    - jmsf1
    - jmsf2
  metadata:
    aa: aa
    bb: bb
  route:
    load-balance: random
    retryable-status-codes:
      - 404
      - 500
      - 502
  circuit-breaker:
    enabled: true
    wait-timeout-in-second: 10
  naming:
    type: consul
    host: 127.0.0.1
    #    token: 123123
    port: 8500
  # 配置中心配置，如果不代码模拟环境变量，下方配置不可缺少
  config:
    type: consul
    host: 127.0.0.1
    #    token: 123123
    port: 8500
  # 服务治理中心配置，如果不代码模拟环境变量，下方配置不可缺少
  governance:
    type: consul
    host: 127.0.0.1
    #    token: 123123
    port: 8500
  # 元数据配置，如果不代码模拟环境变量，下方配置不可缺少
  meta:
    app: jmsf-consumer-demo
    cluster: dev
    group: group1
    namespace: demo
    mesh-group: mesh1
    zone: ${spring.profiles.active}

  swagger:
    enabled: true
#    basePackage: com.jdcloud.jmsf