jmsf:
  enabled: true
  tags:
    - jmsf1
    - jmsf2
  metadata:
    aa: aa
    bb: bb
#  route:
#    load-balance: random
#    retryable-status-codes:
#      - 404
#      - 500
#      - 502
  swagger:
    enabled: true
    basePackage: com.jdcloud.jmsf

spring:
  cloud:
    consul:
      discovery:
        ip-address: 127.0.0.1