jmesh:
  enabled: true
  tags:
    - jmesh1
    - jmesh2
  metadata:
    aa: aa
    bb: bb
#  route:
#    load-balance: random
#    retryable-status-codes:
#      - 404
#      - 500
#      - 502
  swagger:
    enabled: true
#    basePackage: com.jdcloud.jmesh
