---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: jmesh-provider-demo
      provider: jkube
      version: 1.0.0-SNAPSHOT
      group: com.jdcloud.jmesh
    name: jmesh-provider-demo
  spec:
    replicas: 3
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: jmesh-provider-demo
        provider: jkube
        group: com.jdcloud.jmesh
    template:
      metadata:
        labels:
          app: jmesh-provider-demo
          provider: jkube
          version: 1.0.0-SNAPSHOT
          group: com.jdcloud.jmesh
      spec:
        containers:
        - env:
          - name: JMESH_SERVICE_NAME
            value: sc-jmesh-provider
          - name: organization
            value: JMesh
          - name: projectname
            value: JMesh - Spring Cloud Provider Demo
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: tpaas-registry-itg-vpc.jdcloud.com/jmesh/sc-jmesh-provider:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: jmesh-provider-demo
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
