---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: jmsf-provider-demo
      version: 1.0.0-SNAPSHOT
    name: jmsf-provider-demo
  spec:
    replicas: 3
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: jmsf-provider-demo
    template:
      metadata:
        labels:
          app: jmsf-provider-demo
          version: 1.0.0-SNAPSHOT
          app.jindowin.jd.com/name: jmsf-provider-demo
          jmsf.service.jindowin.jd.com/name: jmsf-provider-demo
          # 如果采用Mesh方式接入JMSF值为true
          jmsf.service.jindowin.jd.com/injection: "false"
          group.jindowin.jd.com/name: v1
      spec:
        containers:
        - env:
          - name: JMESH_SERVICE_NAME
            value: jmsf-provider-demo
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: registry.xxx.com/demo/jmsf-provider-demo:1.0.0-SNAPSHOT
          imagePullPolicy: Always
#          lifecycle:
#            postStart:
#              exec:
#                command: [ "/bin/bash", "-c", "curl -s http://sgm-server:8042/local/probe/java/script?app=jmsf-provider-demo -o /tmp/sgm_java.sh;source /tmp/sgm_java.sh" ]
          volumeMounts:
            - mountPath: /export/package/sgm-probe-java
              name: sgm-volume
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: jmsf-provider-demo
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
        initContainers:
          - name: init-env
            # 如果内网无法拉取busybox镜像，可以采用与原业务镜像相同的镜像即可
            image: busybox:1.28
            command: [ '/bin/bash', '-c', "curl -s xxxx" ]
            volumeMounts:
              - mountPath: /export/package/sgm-probe-java
                name: sgm-volume
        volumes:
          - name: sgm-volume
            emptyDir: {}