---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: spring-cloud-jmsf-consumer-demo
      provider: jkube
      version: 1.0.0-SNAPSHOT
      group: com.jdcloud.jmsf
    name: spring-cloud-jmsf-consumer-demo
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: spring-cloud-jmsf-consumer-demo
        provider: jkube
        group: com.jdcloud.jmsf
    template:
      metadata:
        labels:
          app: spring-cloud-jmsf-consumer-demo
          provider: jkube
          version: 1.0.0-SNAPSHOT
          group: com.jdcloud.jmsf
      spec:
        containers:
        - env:
          - name: PROVIDER_NAME
            value: sc-jmsf-provider
          - name: JMESH_SERVICE_NAME
            value: sc-jmsf-consumer
          - name: organization
            value: JMesh
          - name: projectname
            value: JMesh - Spring Cloud Consumer Demo
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: tpaas-registry-itg-vpc.jdcloud.com/jmsf/sc-jmsf-consumer:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: jmsf-spring-cloud-jmsf-consumer-demo
          ports:
          - containerPort: 8081
            name: sunproxyadmin
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
