---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-cloud-demo/provider-demo
      jkube.io/git-url: https://git.jd.com/jmesh/spring-cloud-samples.git
      jkube.io/scm-tag: HEAD
      jkube.io/git-commit: 51aee249dc46ba45ec7ae523008c7c026df815b2
      jkube.io/git-branch: master
    labels:
      expose: "true"
      app: provider-demo
      provider: jkube
      version: 1.0-SNAPSHOT
      group: io.meshware.springcloud
    name: sc-provider
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: provider-demo
      provider: jkube
      group: io.meshware.springcloud
    type: NodePort
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-cloud-demo/provider-demo
      jkube.io/git-url: https://git.jd.com/jmesh/spring-cloud-samples.git
      jkube.io/scm-tag: HEAD
      jkube.io/git-commit: 51aee249dc46ba45ec7ae523008c7c026df815b2
      jkube.io/git-branch: master
    labels:
      app: provider-demo
      provider: jkube
      version: 1.0-SNAPSHOT
      group: io.meshware.springcloud
    name: provider-demo
  spec:
    replicas: 2
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: provider-demo
        provider: jkube
        group: io.meshware.springcloud
    template:
      metadata:
        annotations:
          jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-cloud-demo/provider-demo
          jkube.io/git-url: https://git.jd.com/jmesh/spring-cloud-samples.git
          jkube.io/scm-tag: HEAD
          jkube.io/git-commit: 51aee249dc46ba45ec7ae523008c7c026df815b2
          jkube.io/git-branch: master
        labels:
          app: provider-demo
          provider: jkube
          version: 1.0-SNAPSHOT
          group: io.meshware.springcloud
      spec:
        containers:
        - env:
          - name: JMESH_SERVICE_APP
            value: sc-provider
          - name: JMESH_REGISTRY_HOST
            value: 116.196.114.131
          - name: organization
            value: JMesh
          - name: projectname
            value: provider-demo
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: tpaas-registry-itg-vpc.jdcloud.com/jmesh/sc-provider:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: jmesh-provider-demo
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
