jmsf:
  enabled: true
  tags:
    - jmsf1
    - jmsf2
  metadata:
    aa: aa
    bb: bb
  route:
    load-balance: random
    retryable-status-codes:
      - 404
      - 500
      - 502
  circuit-breaker:
    enabled: true
    wait-timeout-in-second: 10
  # 注册中心配置，替代环境变量
  naming:
    type: jmsfconsul
    host: svc2.meshware.io
    #    token: 123123
    port: 8500
  # 配置中心配置，如果不代码模拟环境变量，下方配置不可缺少
  config:
    type: jmsfconsul
    host: svc2.meshware.io
    #    token: 123123
    port: 8500
  # 服务治理中心配置，如果不代码模拟环境变量，下方配置不可缺少
  governance:
    type: jmsfconsul
    host: svc2.meshware.io
    #    token: 123123
    port: 8500
  # 元数据配置，如果不代码模拟环境变量，下方配置不可缺少
  meta:
    # 建议与服务名称相同
    app: jmsf-consumer-demo
    # 服务名称（JMSF控制台创建的服务名）
    service: ${JMESH_SERVICE_ID:jmsf-consumer-demo}
    # 部署对应的集群信息
    cluster: dev
    # 自定义分组信息
    group: group1
    # 配置JMSF控制台服务创建的对应命名空间
    namespace: demo
    # 配置网格名称
    mesh-group: mesh1
    # 自定义分区信息
    zone: default
