server:
  port: 8081
  servlet:
    context-path: /

management:
  endpoint:
    shutdown:
      enabled: false
    restart:
      enabled: false
    health:
      enabled: true
    refresh:
      enabled: true
  #  server:
  #    port: 4452
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,refresh

logging:
  config: classpath:logback.xml
  level:
    org.springframework.cloud.consul: INFO
    com.jdcloud: ${JMESH_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yy-MM-dd.HH:mm:ss.SSS} [%-16t] %-5p %-22c{0}%X{ServiceId}%X{trace-id} - %m%n"
    file: "%d{yy-MM-dd.HH:mm:ss.SSS} [%-16t] %-5p %-22c{0}%X{ServiceId}%X{trace-id} - %m%n"
  file:
    path: ./logs/
    name: ${logging.file.path}spring.log

spring:
  application:
    name: jmsf-consumer-demo
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    web-application-type: @webApplicationType@
  profiles:
    active: 'develop'

  cloud:
    discovery:
      enabled: true

