server:
  port: 8080
  servlet:
    context-path: /

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#management:
#  server:
#    port: 4452
#  security:
#    enabled: false

logging:
  level:
    org.springframework.cloud.consul: DEBUG
spring:
  application:
    name: ${JMESH_SERVICE_APP:sc-provider}

  profiles:
    active: '@activeProfile@'
